version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: postgis 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      # This is my settings, change them as you prefer
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr # Same name that the database service, here db
      PGADMIN_DEFAULT_PASSWORD: admin # Same password as MYSQL_ROOT_PASSWORD
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    links:
      - database

  mailer:
    image: schickling/mailcatcher
    ports: [ 1025, 1080 ]

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data: ###< doctrine/doctrine-bundle ###
