name: Code quality

on: [push, pull_request]

jobs:
  php_code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: make validate

      - name: Install dependencies
        run: composer install

      - name: Detecting PHP Code Standards Violations
        run: make phpcs

      - name: phpstan
        run: make phpstan

      - name: Twig lint
        run: make twig-lint
