name: Code quality

on: [push, pull_request]

jobs:
  php_code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install

      - name: Detecting PHP Code Standards Violations
        run: ./vendor/bin/phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src

      - name: phpstan
        run: ./vendor/bin/phpstan analyse ./src --level 9

      - name: Twig lint
        run: php bin/console lint:twig ./templates
